import { formatINR, centsToRupees } from "@/lib/money";
import type { Customer, Invoice, InvoiceLine, Organization } from "@prisma/client";

type InvoiceWithRelations = Invoice & {
  customer: Customer | null;
  lines: InvoiceLine[];
  organization: Pick<Organization, "name" | "legalName" | "gstin" | "logoUrl">;
};

export function InvoicePdfDocument({ invoice }: { invoice: InvoiceWithRelations }) {
  const companyName = invoice.organization.legalName || invoice.organization.name;
  const customer = invoice.customer;

  return (
    <div className="mx-auto max-w-3xl bg-white p-8 text-zinc-900 print:p-0">
      <div className="mb-8 flex items-start justify-between border-b border-zinc-300 pb-6">
        <div>
          <h1 className="text-2xl font-bold">{companyName}</h1>
          {invoice.organization.gstin && (
            <p className="mt-1 text-sm text-zinc-600">GSTIN: {invoice.organization.gstin}</p>
          )}
        </div>
        <div className="text-right">
          <p className="text-lg font-semibold">TAX INVOICE</p>
          <p className="text-sm">{invoice.invoiceNumber ?? "DRAFT"}</p>
          {invoice.invoiceDate && (
            <p className="text-sm text-zinc-600">
              Date: {new Date(invoice.invoiceDate).toLocaleDateString("en-IN")}
            </p>
          )}
          {invoice.dueDate && (
            <p className="text-sm text-zinc-600">
              Due: {new Date(invoice.dueDate).toLocaleDateString("en-IN")}
            </p>
          )}
        </div>
      </div>

      {customer && (
        <div className="mb-8">
          <p className="text-xs font-medium uppercase text-zinc-500">Bill to</p>
          <p className="font-semibold">{customer.name}</p>
          {customer.addressLine1 && <p className="text-sm">{customer.addressLine1}</p>}
          {customer.city && (
            <p className="text-sm">
              {[customer.city, customer.billingState, customer.postalCode]
                .filter(Boolean)
                .join(", ")}
            </p>
          )}
          {customer.gstin && <p className="text-sm">GSTIN: {customer.gstin}</p>}
          {customer.phone && <p className="text-sm">Phone: {customer.phone}</p>}
        </div>
      )}

      <table className="mb-8 w-full text-sm">
        <thead>
          <tr className="border-b border-zinc-300">
            <th className="py-2 text-left font-medium">#</th>
            <th className="py-2 text-left font-medium">Description</th>
            <th className="py-2 text-right font-medium">Qty</th>
            <th className="py-2 text-right font-medium">Rate</th>
            <th className="py-2 text-right font-medium">Amount</th>
          </tr>
        </thead>
        <tbody>
          {invoice.lines.map((line, i) => (
            <tr key={line.id} className="border-b border-zinc-100">
              <td className="py-2">{i + 1}</td>
              <td className="py-2">
                {line.description}
                {line.boxName && line.lengthMm && (
                  <span className="block text-xs text-zinc-500">
                    {line.boxName} · {Number(line.lengthMm)}×{Number(line.widthMm)}×
                    {Number(line.heightMm)} mm
                  </span>
                )}
              </td>
              <td className="py-2 text-right">{Number(line.quantity)}</td>
              <td className="py-2 text-right">{formatINR(line.sellingRateCents)}</td>
              <td className="py-2 text-right">{formatINR(line.lineAmountCents)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="ml-auto w-64 space-y-1 text-sm">
        <div className="flex justify-between">
          <span>Subtotal</span>
          <span>{formatINR(invoice.subtotalCents)}</span>
        </div>
        <div className="flex justify-between border-t border-zinc-300 pt-2 text-base font-semibold">
          <span>Grand total</span>
          <span>{formatINR(invoice.grandTotalCents)}</span>
        </div>
        {invoice.amountPaidCents > BigInt(0) && (
          <div className="flex justify-between text-zinc-600">
            <span>Paid</span>
            <span>{formatINR(invoice.amountPaidCents)}</span>
          </div>
        )}
        {invoice.balanceDueCents > BigInt(0) && (
          <div className="flex justify-between font-medium">
            <span>Balance due</span>
            <span>{formatINR(invoice.balanceDueCents)}</span>
          </div>
        )}
      </div>

      {invoice.notes && (
        <div className="mt-8 border-t border-zinc-200 pt-4">
          <p className="text-xs font-medium uppercase text-zinc-500">Notes</p>
          <p className="mt-1 text-sm whitespace-pre-wrap">{invoice.notes}</p>
        </div>
      )}

      <p className="mt-12 text-center text-xs text-zinc-400">
        Generated by PackFlow · Amount in words: {amountInWords(invoice.grandTotalCents)}
      </p>
    </div>
  );
}

function amountInWords(cents: bigint): string {
  const rupees = Math.round(centsToRupees(cents));
  return `Rupees ${rupees.toLocaleString("en-IN")} only`;
}
